### ISSUE TITLE
Output indentation is breaking

### ISSUE THREAD

**Issue by the-glima** [cambridge-healthcare/grunt-stencil#18]
I had a template: **default-page.dot.html**

``` html
<body>
  {{= it.document }}
</body>
```

A page: **index.dot.html**

``` html
{
  "template": "default-page"
}

<div>
  <h1>Title</h1>
</div>
```

And output this:

``` html
<body>
  <div>
  <h1>Title</h1>
</div>
</body>
```

I've tried different places for the  `{{= it.document }}` but still breaks.

**Comment by szymonrw** [comment]
Hi! Thanks for trying grunt-stencil :-)

This is expected behaviour although it might be confusing. `it.document` is literally just pasting the text of the document. No re-identation is done.

This image should explain it better. Notice how all whitespace is preserved.

![explanation](https://cloud.githubusercontent.com/assets/1305140/2810057/a0799506-cd97-11e3-861b-c741aa6d4f68.png)

I think what you're expecting is to have indentation of the line the `{{= it.document }}` is on added to every line of the document. It's not a bad idea but it's actually up to the template engine to do ([doT.js](http://olado.github.io/doT/index.html) is the one we use and it doesn't have this feature).

You might want a proper html prettifier for this.

**Comment by lhwparis** [comment]
i think code indentation would be a cool feature for 2.0 or a future 1.x release?
maybe something like: https://github.com/jonschlinkert/grunt-prettify

**Comment by szymonrw** [comment]
As I've mentioned before: It's up to the template engine. Grunt-stencil doesn't even know the position where the `{{= it.document }}` is (it's the templating engine which does the concatenation).

So it's never going to be implemented in grunt-stencil directly because of this technical reason.

You might want to consider suggesting this feature to [doT.js](https://github.com/olado/doT), the templating engine that we use.

**Comment by lhwparis** [comment]
think its not exaclty that. i agree to preserve the give identaion its the templat engines task but a task to well format the whole html file after the template engine is done can be included in stencil or (runned after stencil)

**Comment by the-glima** [comment]
@szywon I get it, great plugin anyway. Good work.

@lhwparis thanks for the hint, grunt-prettify can handle for now.
