### ISSUE TITLE
Undefined dependencies

### ISSUE THREAD

**Issue by bnadlerjr** [cambridge-healthcare/grunt-stencil#2]
Hi!

After adding grunt-stencil to my package.json file and installing, I got several errors about some packages not being installed. Specifically: underscore, marked and dot. I fixed it by adding them to my package.json file. I'm not sure if those were meant to be runtime dependencies or not (I only see them under devDependencies in stencil's package.json). Just wanted to give you a heads up.

**Comment by szymonrw** [comment]
Thanks for pointing that out. You're absolutely right. They should in `dependencies` instead.

(The reason that we missed that is because we only used it in projects that had them already installed. `grunt-stencil` began it's life in one of our projects.)

Sorry for inconvenience. We'll release a fix later today.

**Comment by szymonrw** [comment]
Version 0.0.3 fixes that. Let me know if that works for you :)

**Comment by bnadlerjr** [comment]
Yep, thanks!
